In [527]:
import json
import pickle
import os

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

from hyperopt import STATUS_OK, Trials, fmin, hp, tpe
from hyperopt.pyll import scope

from sklearn.ensemble import RandomForestRegressor

import yfinance as yf

from sqlalchemy import create_engine


In [528]:
def dump_pickle(obj, filename: str):
    with open(filename, "wb") as f_out:
        return pickle.dump(obj, f_out)


def load_pickle(filename: str):
    with open(filename, "rb") as f_in:
        return pickle.load(f_in)


# Download stock price data
def download_stock_data(ticker, start_date, end_date):
    stock_data = yf.download(ticker, start=start_date, end=end_date)
    return stock_data


# Preprocess data and create input sequences
def preprocess_data(data, sequence_length):
    sequences = []
    for i in range(len(data) - sequence_length):
        sequence = data.iloc[i:i+sequence_length].values
        target = data.iloc[i+sequence_length]
        sequences.append((sequence, target))
    return sequences


# Split data into training and testing sets
def split_data(data, test_size=0.2):
    train_data, test_data = train_test_split(data, test_size=test_size, shuffle=False)
    return train_data, test_data


# Hyperparameter tuning
def run_optimization(num_trials: int = 30):

    X_train, y_train = load_pickle("train.pkl")
    X_test, y_test = load_pickle("test.pkl")

    def objective(params):

        rf = RandomForestRegressor(**params)
        rf.fit(X_train, y_train)
        y_pred = rf.predict(X_test)
        rmse = mean_squared_error(y_test, y_pred, squared=False)

        return {'loss': rmse, 'status': STATUS_OK}

    search_space = {
        'max_depth': scope.int(hp.quniform('max_depth', 1, 20, 1)),
        'n_estimators': scope.int(hp.quniform('n_estimators', 10, 50, 1)),
        'min_samples_split': scope.int(hp.quniform('min_samples_split', 2, 10, 1)),
        'min_samples_leaf': scope.int(hp.quniform('min_samples_leaf', 1, 4, 1)),
        'random_state': 42
    }

    rstate = np.random.default_rng(42)  # for reproducible results
    best_params = fmin(
        fn=objective,
        space=search_space,
        algo=tpe.suggest,
        max_evals=num_trials,
        trials=Trials(),
        rstate=rstate
    )

    return best_params


# Train regression model
def train_model(best_params):
    
    X_train, y_train = load_pickle("train.pkl")
    X_test, y_test = load_pickle("test.pkl")

    new_params = {}
    for param in best_params:
        new_params[param] = int(best_params[param])

    rf = RandomForestRegressor(**new_params)
    model = rf.fit(X_train, y_train)

    y_pred = rf.predict(X_test)

    rmse = mean_squared_error(y_test, y_pred, squared=False)
    
    return model


# Evaluate model on test data
def evaluate_model(model, X_test, y_test):
    
    predictions = model.predict(X_test)
    mse = mean_squared_error(y_test, predictions)
    return mse

In [3]:
# Create a list to append the tickers dataframes (more than 1 ticker)
# dfs = []

In [529]:
# Download stock data
ticker = 'goog'
start_date = '2023-08-01'
end_date = '2024-08-01'

stock_data = download_stock_data(ticker, start_date, end_date)

[*********************100%%**********************]  1 of 1 completed


In [530]:
df = (
    pd.DataFrame(stock_data)
    .reset_index()
    .rename(
        columns={
            "Date": "date",
            "Open": "open",
            "High": "high",
            "Low": "low",
            "Close": "close",
            "Adj Close": "adj_close",
            "Volume": "volume",
        }
    )
)
df["symbol"] = ticker
df = df[["date", "symbol", "open", "high", "low", "close", "adj_close", "volume"]]
df = df.set_index("date")

In [531]:
# Display the first few rows of the DataFrame
df

symbol        open        high         low       close   adj_close  \
date                                                                            
2023-08-01   goog  130.854996  132.919998  130.750000  131.889999  131.740082   
2023-08-02   goog  129.839996  130.419998  127.849998  128.639999  128.493774   
2023-08-03   goog  128.369995  129.770004  127.775002  128.770004  128.623642   
2023-08-04   goog  129.600006  131.929993  128.315002  128.539993  128.393890   
2023-08-07   goog  129.509995  132.059998  129.429993  131.940002  131.790039   
...           ...         ...         ...         ...         ...         ...   
2024-07-25   goog  174.250000  175.199997  169.050003  169.160004  169.160004   
2024-07-26   goog  168.770004  169.839996  165.865005  168.679993  168.679993   
2024-07-29   goog  170.500000  172.160004  169.720001  171.130005  171.130005   
2024-07-30   goog  171.830002  172.949997  170.119995  171.860001  171.860001   
2024-07-31   goog  174.919998  175.910004  171.720001  173.149994  173.149994   

              volume  
date                  
2023-08-01  22154300  
2023-08-02  22705800  
2023-08-03  15018100  
2023-08-04  20509500  
2023-08-07  17621000  
...              ...  
2024-07-25  28967900  
2024-07-26  25150100  
2024-07-29  13768900  
2024-07-30  13681400  
2024-07-31  15650200  

[252 rows x 7 columns]

In [16]:
# (more than 1 ticker)
# dfs.append(df)
# dfs

[           symbol        open        high         low       close   adj_close  \
 date                                                                            
 2020-01-02   goog   67.077499   68.406998   67.077499   68.368500   68.290787   
 2020-01-03   goog   67.392998   68.625000   67.277199   68.032997   67.955666   
 2020-01-06   goog   67.500000   69.824997   67.500000   69.710503   69.631264   
 2020-01-07   goog   69.897003   70.149498   69.518997   69.667000   69.587814   
 2020-01-08   goog   69.603996   70.579002   69.542000   70.216003   70.136192   
 ...           ...         ...         ...         ...         ...         ...   
 2024-07-24   goog  175.389999  177.949997  173.570007  174.369995  174.369995   
 2024-07-25   goog  174.250000  175.199997  169.050003  169.160004  169.160004   
 2024-07-26   goog  168.770004  169.839996  165.865005  168.679993  168.679993   
 2024-07-29   goog  170.500000  172.160004  169.720001  171.130005  171.130005   
 2024-07-30   go

In [17]:
# (more than 1 ticker)
# df = pd.concat(dfs, axis=0)
# df.head()

symbol       open       high        low      close  adj_close  \
date                                                                       
2020-01-02   goog  67.077499  68.406998  67.077499  68.368500  68.290787   
2020-01-03   goog  67.392998  68.625000  67.277199  68.032997  67.955666   
2020-01-06   goog  67.500000  69.824997  67.500000  69.710503  69.631264   
2020-01-07   goog  69.897003  70.149498  69.518997  69.667000  69.587814   
2020-01-08   goog  69.603996  70.579002  69.542000  70.216003  70.136192   

              volume  
date                  
2020-01-02  28132000  
2020-01-03  23728000  
2020-01-06  34646000  
2020-01-07  30054000  
2020-01-08  30560000

In [532]:
# Save historical data to csv 
df.to_csv(f'stocks_{ticker}_{start_date}_to_{end_date}.csv')

In [512]:
# Create connection to postgres instance
db_uri = 'postgresql://postgres:postgres@postgres:5432/stocks'
engine = create_engine(db_uri)

In [513]:
# Insert historical data into postgres table 'stock_ohlc'
df.to_sql('stock_ohlc', con=engine, if_exists='append', index=True) 

252

In [533]:
# Preprocess data
sequence_length = 10
stock_data = stock_data['Adj Close']

data_sequences = preprocess_data(stock_data, sequence_length)

In [435]:
data_sequences[-2:]

[(array([185.5       , 182.61999512, 179.22000122, 179.38999939,
         183.3500061 , 183.6000061 , 174.36999512, 169.16000366,
         168.67999268, 171.13000488]),
  171.86000061035156),
 (array([182.61999512, 179.22000122, 179.38999939, 183.3500061 ,
         183.6000061 , 174.36999512, 169.16000366, 168.67999268,
         171.13000488, 171.86000061]),
  173.14999389648438)]

In [534]:
# Split data into training and testing sets
train_data, test_data = split_data(data_sequences)

In [516]:
# Prepare training data
X_train = np.array([item[0] for item in train_data])
y_train = np.array([item[1] for item in train_data])

# Prepare test data
X_test = np.array([item[0] for item in test_data])
y_test = np.array([item[1] for item in test_data])

# Show the head of the arrays
print(X_train[0:2])
print(y_train[0:2])

[[131.74008179 128.49377441 128.62364197 128.39389038 131.79003906
  131.69013977 130.00205994 130.06199646 130.02203369 131.68016052]
 [128.49377441 128.62364197 128.39389038 131.79003906 131.69013977
  130.00205994 130.06199646 130.02203369 131.68016052 130.12193298]]
[130.12193298 128.96324158]


In [535]:
dump_pickle((X_train, y_train), "train.pkl")
dump_pickle((X_test, y_test), "test.pkl")

In [536]:
# Find best_params for randoforest
best_params = run_optimization()
best_params

100%|██████████| 30/30 [00:01<00:00, 15.12trial/s, best loss: 6.73158424522822] 


{'max_depth': 8.0,
 'min_samples_leaf': 1.0,
 'min_samples_split': 4.0,
 'n_estimators': 32.0}

In [519]:
# Save to json
with open('hpo_best_params_rf.json', 'w') as f:
    json.dump(best_params, f)

In [337]:
with open('hpo_best_params_rf.json', "r") as f:
    best_params = json.load(f)

best_params

{'learning_rate': 0.4583157236029487,
 'max_depth': 82.0,
 'min_child_weight': 12.683009917514006,
 'reg_alpha': 0.09418662500920566,
 'reg_lambda': 0.3424580598862834}

In [537]:
# Train RamdomForest regression model with the best_params
loaded_model = train_model(best_params)

In [538]:
# Save the trained model to pickle
with open(f'rf.bin', 'wb') as f:
    pickle.dump(loaded_model, f)

In [539]:
# Predict over all data
data_sequences_features = np.array([item[0] for item in data_sequences])
data_sequences_target = np.array([item[1] for item in data_sequences])

df_features = pd.DataFrame(data_sequences_features)
df_features

0           1           2           3           4           5  \
0    131.740082  128.493774  128.623642  128.393890  131.790039  131.690140   
1    128.493774  128.623642  128.393890  131.790039  131.690140  130.002060   
2    128.623642  128.393890  131.790039  131.690140  130.002060  130.061996   
3    128.393890  131.790039  131.690140  130.002060  130.061996  130.022034   
4    131.790039  131.690140  130.002060  130.061996  130.022034  131.680161   
..          ...         ...         ...         ...         ...         ...   
237  187.300003  186.779999  188.190002  185.500000  182.619995  179.220001   
238  186.779999  188.190002  185.500000  182.619995  179.220001  179.389999   
239  188.190002  185.500000  182.619995  179.220001  179.389999  183.350006   
240  185.500000  182.619995  179.220001  179.389999  183.350006  183.600006   
241  182.619995  179.220001  179.389999  183.350006  183.600006  174.369995   

              6           7           8           9  
0    130.002060  130.061996  130.022034  131.680161  
1    130.061996  130.022034  131.680161  130.121933  
2    130.022034  131.680161  130.121933  128.963242  
3    131.680161  130.121933  128.963242  130.311722  
4    130.121933  128.963242  130.311722  127.964386  
..          ...         ...         ...         ...  
237  179.389999  183.350006  183.600006  174.369995  
238  183.350006  183.600006  174.369995  169.160004  
239  183.600006  174.369995  169.160004  168.679993  
240  174.369995  169.160004  168.679993  171.130005  
241  169.160004  168.679993  171.130005  171.860001  

[242 rows x 10 columns]

In [540]:
predictions = loaded_model.predict(pd.DataFrame(data_sequences_features))
#predictions = loaded_model.predict([[187.929993, 183.750000, 183.130005, 182.550003, 186.410004, 180.830002, 179.850006, 182.500000, 183.199997, 181.710007]])
predictions[-230:]

array([137.1109207 , 137.17398563, 136.94135193, 136.07262091,
       136.26680192, 136.85809963, 137.25843252, 137.28136013,
       137.16430031, 137.95078592, 138.48546065, 138.0774467 ,
       138.59630336, 136.16040208, 132.38675774, 131.26261329,
       131.86895261, 130.751833  , 131.01920562, 132.59284802,
       131.84326389, 134.14496246, 134.14250879, 134.92753889,
       136.43050092, 137.24469252, 138.56422558, 138.96508991,
       140.58318588, 140.61301877, 135.385519  , 139.45589366,
       140.41861721, 140.3043068 , 139.10239413, 137.74273439,
       137.0812969 , 139.07852018, 134.14188732, 125.90983121,
       124.9483484 , 125.32266357, 125.79024908, 126.4830706 ,
       128.27873011, 129.7317363 , 130.77191377, 132.07331303,
       132.61577505, 132.40764294, 133.64246102, 133.58327727,
       135.01457435, 136.2689633 , 137.21858232, 138.3222903 ,
       137.62373784, 138.76744387, 138.65129265, 137.707344  ,
       138.34078258, 138.18825461, 136.92467132, 134.78

In [541]:
# Complete the sequence_length of null values with zero
zero_data = np.zeros(shape=(sequence_length,1))
predictions = np.append(zero_data, predictions)
predictions

array([  0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        , 131.20387898, 129.68237191,
       130.33814751, 128.87708107, 128.97364938, 129.91223888,
       131.12860997, 130.78452757, 130.73802088, 131.56621474,
       133.21745146, 136.01997387, 137.1109207 , 137.17398563,
       136.94135193, 136.07262091, 136.26680192, 136.85809963,
       137.25843252, 137.28136013, 137.16430031, 137.95078592,
       138.48546065, 138.0774467 , 138.59630336, 136.16040208,
       132.38675774, 131.26261329, 131.86895261, 130.751833  ,
       131.01920562, 132.59284802, 131.84326389, 134.14496246,
       134.14250879, 134.92753889, 136.43050092, 137.24469252,
       138.56422558, 138.96508991, 140.58318588, 140.61301877,
       135.385519  , 139.45589366, 140.41861721, 140.3043068 ,
       139.10239413, 137.74273439, 137.0812969 , 139.07852018,
       134.14188732, 125.90983121, 124.9483484 , 125.32

In [542]:
df['prediction'] = pd.DataFrame(predictions).values
df['model'] = 'randomforest'
df.reset_index(inplace=True)
columns = ['date', 'symbol', 'prediction', 'model']
df = pd.DataFrame(df, columns=columns)

df.head(15)
#df.sort_values(by=['date'], inplace=False, ascending=False).head(20)

date symbol  prediction         model
0  2023-08-01   goog    0.000000  randomforest
1  2023-08-02   goog    0.000000  randomforest
2  2023-08-03   goog    0.000000  randomforest
3  2023-08-04   goog    0.000000  randomforest
4  2023-08-07   goog    0.000000  randomforest
5  2023-08-08   goog    0.000000  randomforest
6  2023-08-09   goog    0.000000  randomforest
7  2023-08-10   goog    0.000000  randomforest
8  2023-08-11   goog    0.000000  randomforest
9  2023-08-14   goog    0.000000  randomforest
10 2023-08-15   goog  131.203879  randomforest
11 2023-08-16   goog  129.682372  randomforest
12 2023-08-17   goog  130.338148  randomforest
13 2023-08-18   goog  128.877081  randomforest
14 2023-08-21   goog  128.973649  randomforest

In [543]:
# Insert historical data into postgres table 'stock_prediction'
df.to_sql('stock_prediction', con=engine, if_exists='append', index=False) 

252

# Usando sql

In [137]:
def get_prediction_historical(data, sequence_length):
    sequences = []
    for i in range(len(data) - sequence_length):
        sequence = data[i:i+sequence_length].values
        
        sequence = sequence.reshape(1,-1)
        
        valid = xgb.DMatrix(sequence)
        #prediction = model.predict(predict_sequence_valid)[0]
        #stock_data.iloc[i+sequence_length]=model.predict(predict_sequence_valid)[0]
        #stock_data.at[i+sequence_length, 'prediction']=model.predict(valid)[0]
        #target = data[i+sequence_length]
        #sequences.append((sequence, target))
    #return sequences

In [138]:
stock_data = stock_data['Adj Close']
prediction_historical = get_prediction_historical(stock_data, sequence_length)

KeyError: 'Adj Close'

In [142]:
stock_data = stock_data['Adj Close']
print(len(stock_data) - sequence_length)

1142


In [187]:
predictions = model.predict(data_sequences_valid)
mse = mean_squared_error(data_sequences_target, predictions)
print(f"mse: {mse}")
print(predictions)

mse: 51.01241725825904
[ 72.48742   73.88183   74.205215 ... 149.50502  149.50502  149.50502 ]


In [175]:
df1 = df.copy()
df1.shape[0]

1152

In [118]:
def get_prediction(date, symbol):
    sql_txt = f"select seq.adj_close from (select date, symbol, adj_close from stock_ohlc where symbol='{symbol}' and date < '{date}' order by date desc limit 10) seq order by seq.date asc;"
    predict_sequence = pd.read_sql_query(sql_txt, con=engine)
    
    #predict_sequence_ser = predict_sequence["adj_close"].squeeze()

    predict_sequence = predict_sequence.to_numpy()
    #print(f"\nla serie en este paso queda: {predict_sequence}")
    #print(f"el tipo es: {type(predict_sequence)}")
    
    predict_sequence = predict_sequence.reshape(1,-1)
    predict_sequence_valid = xgb.DMatrix(predict_sequence)
    prediction = model.predict(predict_sequence_valid)[0]
    return prediction

In [119]:
sql_txt = f"select date, symbol, adj_close from stock_ohlc where symbol='{ticker}' order by date asc;"
historical_data = pd.read_sql_query(sql_txt,con=engine)


In [120]:
for index, row in historical_data.iterrows():
    #print(row['date'], row['symbol'], row['adj_close'], get_prediction(row['date'], row['symbol']))
    historical_data.at[index, 'prediction'] = get_prediction(row['date'], row['symbol'])

In [121]:
historical_data['model']='xgboost'
historical_data.sort_values(by=['date'], inplace=True, ascending=False)
historical_data.head()

date symbol   adj_close  prediction    model
1152  2024-08-12 00:00:00   goog  163.949997   149.50502  xgboost
1151  2024-07-31 00:00:00   goog  173.149994   149.50502  xgboost
1150  2024-07-30 00:00:00   goog  171.860001   149.50502  xgboost
1149  2024-07-29 00:00:00   goog  171.130005   149.50502  xgboost
1148  2024-07-26 00:00:00   goog  168.679993   149.50502  xgboost

In [105]:
# Insert historical data into postgres table 'stock_prediction'
historical_data.to_sql('stock_prediction', con=engine, if_exists='append', index=False) 

153

In [92]:
get_prediction('2024-08-12', 'goog')

array([149.50502], dtype=float32)

In [ ]:
# Last test sequence
X_test[-1]

In [252]:
last_sequence = X_test[-1].reshape(1,-1)
last_sequence

array([[182.61999512, 179.22000122, 179.38999939, 183.3500061 ,
        183.6000061 , 174.36999512, 169.16000366, 168.67999268,
        171.13000488, 171.86000061]])

In [253]:
last_sequence_valid = xgb.DMatrix(last_sequence, label=y_test)
predicted_price = model.predict(last_sequence_valid)[0]
predicted_price

149.50502

In [32]:
# Evaluate model using Mean Squared Error
mse = evaluate_model(model, X_test, y_test)

# Evaluate model using R-squared
r2 = r2_score(y_test, model.predict(X_test))

TypeError: ('Expecting data to be a DMatrix object, got: ', <class 'numpy.ndarray'>)

In [33]:
# Calculate Adjusted R-squared (adjusts for number of features)
n = X_test.shape[0]  # Number of samples
p = X_test.shape[1]  # Number of features

print(f"Number of samples: {n}")
print(f"Number of features: {p}")

Number of samples: 229
Number of features: 10


In [34]:
adjusted_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

# Print the R-squared and adjusted R-squared
print(f'\nR-squared: {r2:.4f}')
print(f'Adjusted R-squared: {adjusted_r2:.2f}')
print(f'Mean Squared Error on Test Data: {mse: 0.2f}')

NameError: name 'r2' is not defined

# Some Testings from here

In [40]:
stock_data.reset_index(inplace=True)
stock_data.head()

Date        Open        High         Low       Close   Adj Close  \
0 2024-08-01  171.979996  175.679993  170.509995  172.449997  172.449997   

     Volume  
0  17177800

In [41]:
stock_data['Date'] = stock_data['Date'].astype(str)
stock_data.head()

Date        Open        High         Low       Close   Adj Close  \
0  2024-08-01  171.979996  175.679993  170.509995  172.449997  172.449997   

     Volume  
0  17177800

In [49]:
stock_data_json = stock_data.to_json(orient='records')
stock_data_json

'[{"Date":"2024-08-01","Open":171.9799957275,"High":175.6799926758,"Low":170.5099945068,"Close":172.4499969482,"Adj Close":172.4499969482,"Volume":17177800}]'

In [57]:
df = pd.read_json(stock_data_json).T
df.head()

/tmp/ipykernel_1779/2030565896.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(stock_data_json).T


0
Date   2024-08-01 00:00:00
Open            171.979996
High            175.679993
Low             170.509995
Close           172.449997

In [17]:
data = stock_data.to_json()
data

'{"Date":{"0":1722816000000},"Open":{"0":154.2100067139},"High":{"0":162.9600067139},"Low":{"0":151.6100006104},"Close":{"0":161.0200042725},"Adj Close":{"0":161.0200042725},"Volume":{"0":82961700}}'

In [8]:
stock_data.describe()

count    1043.000000
mean      109.024967
std        25.535614
min        52.646080
25%        88.299908
50%       111.823158
75%       132.402542
max       153.334015
Name: Adj Close, dtype: float64